server:
  port: 8070
  servlet:
    session:
      cookie:
        name: CLIENT-SESSION

spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client-authorization-code:
            provider: isva
            client-id: client_authcode
            client-secret: ahwoaor82noawasg
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile
            client-name: messaging-client-authorization-code
        provider:
          isva:
            authorization-uri: http://www.iamlab.ibm.com/isvaop/oauth2/authorize
            token-uri: http://www.iamlab.ibm.com/isvaop/oauth2/token
            user-info-uri: http://www.iamlab.ibm.com/isvaop/oauth2/userInfo
            user-name-attribute: uid
            user-info-authentication-method: form

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
